### ISSUE TITLE
Extensive code duplication in GSF decoding

### ISSUE THREAD

**Issue by jamesba** [bbc/rd-apmm-python-lib-mediagrains#67]
The GSF synchronous and asynchronous decoding code paths are nearly identical, and yet because IO and processing are heavily intertwined they have to be repeated rather than written once and reused. This is suboptimal, to say the least.

Suggested Fix: Refactor the code-path so that IO to load an entire block worth of data into a memory buffer is performed upon block entry, and then the various `read_` methods source data from this memory buffer. That way the IO routine can be swapped out for sync and async code paths, but the rest of the code can be shared between the two.

**Comment by simonrankine** [comment]
@jamesba did #66 resolve this issue, and if so can this issue now be close?

**Comment by j616** [comment]
Moved to pivotal https://www.pivotaltracker.com/story/show/170049813
